# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

match(
    type: "appstore",
    readonly: true,
    )

match(
    type: "development",
    readonly: true,
    )

default_platform(:ios)

platform :ios do

  lane :setup_ci_certs do
    setup_ci
    sync_code_signing(
      type: "appstore",
      readonly: true
    )
    sync_code_signing(
      type: "development",
      readonly: true
    )
  end


  lane :beta do
    desc "Push a new beta build to TestFlight"
    setup_ci if ENV['CI']
    build_app(
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive",
    )
    upload_to_testflight(
        skip_waiting_for_build_processing: true
    )
  end
end
