# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)
#
# platform :ios do
#   desc "Push a new release build to the App Store"
#   lane :release do
#     build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
#     upload_to_app_store
#   end
# end

default_platform(:ios)

platform :ios do

  desc "Get certificates"
  lane :certificates do
    sync_code_signing(
      type: "development",
      app_identifier: ['finance.get10101.app'],
      force_for_new_devices: true,
      readonly: true
    )

    # You can repeate the sync_code_signing with other types of certificates such as appstore and adhoc
    sync_code_signing(
      type: "appstore",
      app_identifier: 'finance.get10101.app',
      readonly: true
    )
  end

  desc "Generate new certificates"
  lane :generate_new_certificates do

    sync_code_signing(
      type: "development",
      app_identifier: ['finance.get10101.app'],
      force_for_new_devices: true,
      readonly: false
    )

    sync_code_signing(
      type: "appstore",
      app_identifier: ['finance.get10101.app'],
      force_for_new_devices: true,
      readonly: false
    )

  end

  desc "deploy"
    lane :deploy do
      desc "Push a new beta build to TestFlight"

      setup_ci

      match(
          type: "appstore",
          readonly: true,
      )

#       sync_code_signing(
#         type: "appstore",
#         app_identifier: 'finance.get10101.app',
#         readonly: false
#       )

      build_app(scheme: "appstore")
      upload_to_testflight(
        skip_waiting_for_build_processing: true
      )
    end

end