name: Setup Flutter FVM Environment
description: "Setup FVM, Flutter for building Flutter apps."

inputs:
  fvm_config:
    description: "Path to fvm config file."
    required: false
  working_dir:
    description: "The directory to run these steps in"
    required: false

runs:
  using: composite
  steps:
    - uses: kuhnroyal/flutter-fvm-config-action@v2
      id: fvm-config-action
      with:
        path: ${{ inputs.fvm_config }}

    - uses: subosito/flutter-action@v2
      with:
        cache: true
        flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
        channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

    - name: install fvm (linux)
      if: runner.os == 'Linux'
      shell: bash
      working-directory: ${{inputs.working_dir}}
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew tap leoafarias/fvm
        brew install fvm
        echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
        fvm install

    - name: install fvm (macos)
      if: runner.os == 'macOS'
      shell: bash
      working-directory: ${{inputs.working_dir}}
      run: |
        brew tap leoafarias/fvm
        brew install fvm
        echo "/opt/homebrew/bin" >> $GITHUB_PATH
        fvm install
