name: 'Auto Assign'
on: pull_request_target

jobs:
  assign-pr-author:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: ".github/auto_assign.yml"
