name: publish-docker

on:
  workflow_call:
    inputs:
      tag:
        required: true
        description: "The branch, tag or SHA to checkout."
        type: string
      binary:
        required: true
        description: "The binary to release, either maker or coordinator"
        type: string
      arch:
        required: true
        description: "The target architecture, e.g. x86_64-unknown-linux-gnu, x86_64"
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        shell: bash
        working-directory: ${{ input.binary }}
    steps:
      - name: Checkout tagged commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.ref }}

      - name: Setup rust toolchain
        run: rustup show

      - uses: Swatinem/rust-cache@v2.0.1

      - name: Login into github registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          # Note: if you want to fork this repo and push a container to your fork, you need to change this line to
          # username: ${{ github.actor }}
          username: ${{ github.repository }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ input.binary }}
        run: cargo build --release --bin ${{input.binary}} --target-dir ./target --target= ${{input.arch}}

      - uses: ksm2/archive-action@v1
        id: archive
        with:
          format: "zip"
          name: ${{input.binary}}-${{input.arch}}
          include: ./target/x86_64-unknown-linux-gnu/release/${{ input.binary }}

      - name: Upload ${{ input.binary }} to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: ${{input.binary}}-${{input.arch}}.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
