name: "Attach binaries to GitHub release"

on:
  release:
    types: [created]

jobs:
  build_testflight_release:
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/ios.yml
    secrets: inherit
    with:
      electrs_endpoint: blockstream.info:110
      coordinator_p2p_endpoint: 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156@34.30.20.202:9045
      tag: ${{ github.event.release.target_commitish }}
