name: "Attach binaries to GitHub release"

on:
  release:
    types: [created]

jobs:
  build_testflight_release:
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/ios.yml
    secrets: inherit
    with:
      electrs_endpoint: ${{ secrets.ELECTRS_MAINNET }}
      coordinator_p2p_endpoint: ${{ secrets.COORDINATOR_P2P_ENDPOINT_MAINNET }}
      tag: ${{ github.event.release.target_commitish }}
