name: "Create release"

on:
  pull_request:
    types:
      - closed

env:
  FLUTTER_VERSION: "3.7.7"
  RUST_VERSION: "1.68.0"

jobs:
  release:
    needs: build
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract version from branch name
        id: extract-version
        shell: python
        run: |
          branch_name = "${{ github.event.pull_request.head.ref }}"
          version = branch_name.split("/")[1]

          print(f"::set-output name=version::{version}")

      - name: Extract changelog section for release
        id: changelog
        uses: coditory/changelog-parser@v1
        with:
          version: ${{ steps.extract-version.outputs.version }}

      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.ANDROID_APK_NAME }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ needs.build.outputs.ANDROID_APK_NAME }}
          body: ${{ steps.changelog.outputs.description }}
          token: ${{ secrets.GH_ACTION_TOKEN }}
          tag: ${{ steps.extract-version.outputs.version }}
