name: Release Workflow

on:
  push:
    branches:
      - "main"
# TODO: trigger this regularly, e.g. nightly

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
  APP_SPECIFIC_PASSWORD: ${{ secrets.MATCHAPP_SPECIFIC_PASSWORD_PASSWORD }}
  GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
  CI: true

jobs:
  release-to-testflight:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - name: Add signing certificates
        working-directory: mobile/ios
        run: |
          MATCH_PASSWORD=$MATCH_PASSWORD FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=$APP_SPECIFIC_PASSWORD MATCH_GIT_BASIC_AUTHORIZATION=$GIT_BASIC_AUTHORIZATION fastlane setup_ci_certs --verbose
          security find-identity -v -p codesigning
      - name: Show codesigning ids
        run: security find-identity -v -p codesigning
      - name: Setup rust toolchain
        run: rustup show
      - uses: Swatinem/rust-cache@v2.2.0
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install FFI bindings
        uses: baptiste0928/cargo-install@v1
        with:
          crate: flutter_rust_bridge_codegen
          version: "1.63.1"
      - name: Generate FFI bindings
        run: just gen
      - name: Build deps
        run: just deps-ios
      - name: Build ios files
        run: just ios
      - name: Build ios package
        working-directory: mobile/ios
        run: flutter build ios
      - run: MATCH_PASSWORD=$MATCH_PASSWORD FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=$APP_SPECIFIC_PASSWORD MATCH_GIT_BASIC_AUTHORIZATION=$GIT_BASIC_AUTHORIZATION fastlane beta --verbose
